language: php

dist: xenial

services:
  - mysql
  - postgresql

addons:
  apt:
    packages:
      - tidy

env:
  global:
     - TRAVIS_NODE_VERSION="10"

matrix:
  include:
    - php: '7.1'
      env: DB=MYSQL PHPUNIT_TEST=1
    - php: '7.1'
      env: DB=PGSQL PHPUNIT_TEST=1
    - php: '7.2'
      env: DB=MYSQL PHPUNIT_TEST=1 PHPCS_TEST=1
    - php: '7.3'
      env: DB=MYSQL PHPUNIT_COVERAGE_TEST=1
    - php: '7.3'
      env: DB=MYSQL NPM_TEST=1

before_script:
  # Init PHP
  - phpenv rehash
  - phpenv config-rm xdebug.ini
  - export PATH=~/.composer/vendor/bin:$PATH
  - echo 'memory_limit = 2G' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

  # Install composer
  - composer validate
  - if [[ $DB == PGSQL ]]; then composer require --prefer-source --no-update silverstripe/postgresql:^2; fi
  - composer require --no-update silverstripe/recipe-testing:^1 silverstripe/recipe-cms:^4
  - composer install --prefer-source

  # Install NPM dependencies
  - if [[ $NPM_TEST ]]; then nvm install $TRAVIS_NODE_VERSION && nvm use $TRAVIS_NODE_VERSION && npm install -g yarn && yarn install --network-concurrency 1 && (cd vendor/silverstripe/admin && yarn install --network-concurrency 1) && yarn run build; fi

script:
  - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit; fi
  - if [[ $PHPCS_TEST ]]; then vendor/bin/phpcs src tests; fi
  - if [[ $NPM_TEST ]]; then git diff-files --quiet -w --relative=client; fi
  - if [[ $NPM_TEST ]]; then git diff --name-status --relative=client; fi
  - if [[ $NPM_TEST ]]; then yarn run coverage; fi
  - if [[ $NPM_TEST ]]; then yarn run lint; fi
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml; fi

after_success:
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then bash <(curl -s https://codecov.io/bash) -f coverage.xml -F php; fi
  - if [[ $NPM_TEST ]]; then bash <(curl -s https://codecov.io/bash) -F js; fi
